# Generated by Django 5.2 on 2026-07-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingregistration",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
